/**
 * Hero Section Component
 * Auto-generated by tpl-frontend-react-landing
 */
import React from 'react';

export const Hero: React.FC = () => {
  const handlePrimaryCTA = () => {
    window.location.href = '/request';
  };

  const handleSecondaryCTA = () => {
    document.querySelector('.features-section')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <section className="relative overflow-hidden py-20 sm:py-32" style={{ backgroundColor: 'white' }}>
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          {/* Brand/Logo - Now Larger and More Prominent */}
          <div className="mb-6">
            <h1 style={{ 
              fontSize: '3.5rem',
              fontWeight: 'bold',
              background: 'linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
              letterSpacing: '-0.02em',
              marginBottom: '0',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0'
            }}>
              Feedback
              <span style={{ 
                position: 'relative',
                display: 'inline-flex',
                alignItems: 'center',
                marginLeft: '0.1em'
              }}>
                36
                <span style={{
                  display: 'inline-block',
                  width: '0.6em',
                  height: '0.6em',
                  border: '0.08em solid currentColor',
                  borderRadius: '50%',
                  position: 'relative',
                  marginLeft: '-0.05em'
                }}>
                  <span style={{
                    position: 'absolute',
                    top: '-0.15em',
                    right: '-0.15em',
                    width: '0.25em',
                    height: '0.25em',
                    borderTop: '0.08em solid currentColor',
                    borderRight: '0.08em solid currentColor',
                    transform: 'rotate(45deg)'
                  }}></span>
                </span>
              </span>
            </h1>
          </div>

          {/* Headline - Now Secondary */}
          <h2 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl" style={{
            fontSize: 'clamp(1.75rem, 4vw, 2.5rem)',
            lineHeight: '1.2',
            marginBottom: '1.5rem',
            color: '#111827',
            fontWeight: '700'
          }}>
            Get Complete Perspective, Anonymously
          </h2>

          {/* Subtitle */}
          <p className="mt-6 text-lg leading-8 text-gray-600" style={{
            fontSize: '1.125rem',
            lineHeight: '1.75',
            color: '#4b5563',
            marginBottom: '2.5rem'
          }}>
            Request honest feedback from multiple people. Anonymous responses give you the 360° view you need to grow professionally and personally.
          </p>

          {/* CTAs */}
          <div className="mt-10 flex items-center justify-center gap-x-6" style={{ gap: '1rem' }}>
            <button
              onClick={handlePrimaryCTA}
              style={{
                padding: '1rem 2rem',
                background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
                color: 'white',
                border: 'none',
                borderRadius: '8px',
                fontSize: '1.1rem',
                fontWeight: '600',
                cursor: 'pointer',
                boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)',
                transition: 'all 0.2s'
              }}
              onMouseOver={(e) => {
                e.currentTarget.style.transform = 'translateY(-2px)';
                e.currentTarget.style.boxShadow = '0 6px 20px rgba(59, 130, 246, 0.4)';
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 4px 12px rgba(59, 130, 246, 0.3)';
              }}
            >
              Request Feedback
            </button>
            <button
              onClick={handleSecondaryCTA}
              style={{
                padding: '1rem 2rem',
                background: 'transparent',
                color: '#374151',
                border: 'none',
                fontSize: '1rem',
                fontWeight: '600',
                cursor: 'pointer',
                transition: 'color 0.2s'
              }}
              onMouseOver={(e) => {
                e.currentTarget.style.color = '#111827';
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.color = '#374151';
              }}
            >
              Learn More <span aria-hidden="true">→</span>
            </button>
          </div>

          {/* Social Proof (Optional) */}
          <div className="mt-10 flex items-center justify-center gap-x-6 text-sm text-gray-500" style={{
            display: 'flex',
            gap: '2rem',
            marginTop: '2.5rem',
            fontSize: '0.9rem',
            color: '#6b7280',
            flexWrap: 'wrap',
            justifyContent: 'center'
          }}>
            <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '1.2rem' }}>✨</span> 100% Anonymous
            </p>
            <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '1.2rem' }}>⚡</span> 2-minute setup
            </p>
            <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '1.2rem' }}>🔒</span> Private & Secure
            </p>
          </div>
        </div>
      </div>

      {/* Background decorations */}
      <div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
        <div className="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-blue-200 to-cyan-200 opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" />
      </div>
    </section>
  );
};

export default Hero;
