#!/usr/bin/env python3
"""
Stripe Setup Helper for Feedback360
Creates products and prices in your Stripe account
"""
import os
import stripe
from dotenv import load_dotenv

def setup_stripe_products():
    """Create Stripe products and prices for Feedback360"""
    load_dotenv()
    
    api_key = os.getenv("STRIPE_SECRET_KEY")
    if not api_key:
        print("❌ STRIPE_SECRET_KEY not found in .env file")
        print("   1. Create a Stripe account at: https://dashboard.stripe.com")
        print("   2. Get your test API key from: https://dashboard.stripe.com/test/apikeys")
        print("   3. Add it to your .env file: STRIPE_SECRET_KEY=sk_test_...")
        return False
    
    if api_key.startswith("sk_test_51QGjZdGt9vZpMqGgabcdef"):
        print("❌ Please replace the placeholder API key with your actual Stripe key")
        return False
    
    stripe.api_key = api_key
    
    try:
        print("🚀 Setting up Feedback360 products in Stripe...")
        
        # Create Pro product
        pro_product = stripe.Product.create(
            name="Feedback360 Pro",
            description="Limited monthly free-text feedback requests with professional features",
            images=["https://feedback360.app/images/pro-logo.png"],  # Replace with actual logo
            metadata={
                "tier": "pro",
                "app": "feedback360"
            }
        )
        print(f"✅ Created Pro product: {pro_product.id}")
        
        # Create Pro price (£9.99/month)
        pro_price = stripe.Price.create(
            product=pro_product.id,
            currency="gbp",
            unit_amount=999,  # £9.99 in pence
            recurring={
                "interval": "month",
                "interval_count": 1,
                "trial_period_days": 14  # 14-day free trial
            },
            metadata={
                "tier": "pro"
            }
        )
        print(f"✅ Created Pro price: {pro_price.id} (£9.99/month)")
        
        # Create Premium product
        premium_product = stripe.Product.create(
            name="Feedback360 Premium",
            description="Unlimited free-text feedback requests with enterprise features",
            images=["https://feedback360.app/images/premium-logo.png"],
            metadata={
                "tier": "premium",
                "app": "feedback360"
            }
        )
        print(f"✅ Created Premium product: {premium_product.id}")
        
        # Create Premium price (£29.99/month)
        premium_price = stripe.Price.create(
            product=premium_product.id,
            currency="gbp",
            unit_amount=2999,  # £29.99 in pence
            recurring={
                "interval": "month",
                "interval_count": 1,
                "trial_period_days": 14
            },
            metadata={
                "tier": "premium"
            }
        )
        print(f"✅ Created Premium price: {premium_price.id} (£29.99/month)")
        
        # Update .env file
        env_updates = f"""

# Updated Stripe Configuration (Generated by setup_stripe.py)
PRICE_ID_PRO={pro_price.id}
PRICE_ID_PREMIUM={premium_price.id}
PRODUCT_ID_PRO={pro_product.id}
PRODUCT_ID_PREMIUM={premium_product.id}
"""
        
        with open(".env", "a") as f:
            f.write(env_updates)
        
        print("\n🎉 Stripe setup complete!")
        print(f"📝 Updated .env file with new price IDs")
        print(f"\n📋 Next steps:")
        print(f"   1. Set up webhooks at: https://dashboard.stripe.com/test/webhooks")
        print(f"   2. Add endpoint: http://localhost:8000/api/stripe/webhook")
        print(f"   3. Select events: checkout.session.completed, customer.subscription.*")
        print(f"   4. Copy webhook secret to .env: STRIPE_WEBHOOK_SECRET=whsec_...")
        
        return True
        
    except stripe.error.AuthenticationError:
        print("❌ Invalid Stripe API key. Please check your STRIPE_SECRET_KEY")
        return False
    except Exception as e:
        print(f"❌ Error setting up Stripe: {e}")
        return False

if __name__ == "__main__":
    setup_stripe_products()