#!/bin/bash

echo "💾 CLOSING DEVELOPMENT SESSION SAFELY"
echo "====================================="
echo ""
echo "📊 Current session summary:"
echo "  📅 Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "  📁 Repository: control_tower"
echo "  🔧 Timeline system: OPERATIONAL"
echo ""

# Save session state document
SESSION_FILE="SESSION_STATE_$(date '+%Y%m%d_%H%M%S').md"
echo "💾 Saving session state document..."

cat > "$SESSION_FILE" << EOF
# Control Tower Development Session State

**Session Date**: $(date '+%Y-%m-%d %H:%M:%S')
**Repository**: control_tower
**Branch**: $(git branch --show-current 2>/dev/null || echo 'unknown')

## 🎯 System Status

- ✅ Timeline-driven development system: **OPERATIONAL**
- ✅ Requirements parser: **FUNCTIONAL**
- ✅ Priority calculation: **ACTIVE**
- ✅ What-next recommendations: **WORKING**
- ✅ Clean output format: **IMPLEMENTED**
- ✅ Hierarchy context display: **COMPLETE**

## 📊 Current Metrics

EOF

if [ -f "data/timeline_analysis.json" ]; then
    echo "- **Total Requirements**: $(python3 -c "import json; data=json.load(open('data/timeline_analysis.json')); print(len(data['requirements']))" 2>/dev/null || echo 'N/A')" >> "$SESSION_FILE"
    echo "- **Active North Stars**: $(python3 -c "import json; data=json.load(open('data/timeline_analysis.json')); print(len([r for r in data['requirements'] if r.startswith('NS-')]))" 2>/dev/null || echo 'N/A')" >> "$SESSION_FILE"
    echo "- **Development Items Ready**: $(python3 -c "import json; data=json.load(open('data/timeline_analysis.json')); reqs=data['requirements']; dev_levels=['task','layer','feature','workpackage']; print(len([r for r_id,r in reqs.items() if r['level'] in dev_levels and r['progress'] < 100]))" 2>/dev/null || echo 'N/A')" >> "$SESSION_FILE"
else
    echo "- **Timeline Data**: Not available" >> "$SESSION_FILE"
fi

cat >> "$SESSION_FILE" << EOF

## 🔄 Current Recommended Action

\`\`\`
EOF

if [ -f "scripts/timeline_processor.py" ]; then
    python3 scripts/timeline_processor.py 2>/dev/null | tail -n 10 >> "$SESSION_FILE" || echo "Timeline processor output not available" >> "$SESSION_FILE"
fi

cat >> "$SESSION_FILE" << EOF
\`\`\`

## 📋 Outstanding Tasks

1. **Define North Star requirements** - Populate placeholder templates with actual business objectives
2. **Complete requirements cascade** - Ensure proper hierarchy from North Stars → Projects → Systems → Features → Layers → Tasks
3. **Create requirements health check** - Build validation tool for requirements integrity
4. **Build metrics dashboard** - Show completion percentages and financial metrics at all levels

## 🔧 Key Components Completed This Session

- Enhanced timeline processor with development-focused prioritization
- Clean what-next output format (summary + action only)
- Meaningful hierarchy context display
- Proper project extraction for make prep commands
- Session management with safe close functionality

## ⚡ Next Session Workflow

1. \`make what-next\` - Check current priorities
2. \`make prep PROJECT=<project>\` - Prepare work environment
3. Work on recommended action
4. Update progress in requirements files
5. \`make session-close\` - Save state and close safely

---
Generated by Control Tower session management system
EOF

echo "✅ Session state saved to: $SESSION_FILE"
echo ""

# Git safety checkpoint for Control Tower
echo "🔒 Control Tower git safety checkpoint..."
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  Uncommitted changes detected in Control Tower:"
    git status --short
    echo ""
    echo "🔒 Creating safety checkpoint..."
    git add .
    if git commit -m "Session checkpoint: $(date '+%Y-%m-%d %H:%M:%S') - Timeline system state save"; then
        echo "✅ Control Tower changes committed locally"
        echo ""
        echo "🚀 Pushing Control Tower changes to remote..."
        if git push; then
            echo "✅ Control Tower changes pushed to remote repository"
        else
            echo "⚠️  Push failed - check network connection or permissions"
        fi
    else
        echo "⚠️  Commit failed - manual review needed"
    fi
else
    echo "✅ Control Tower repository is clean - no uncommitted changes"
fi

echo ""
echo "📦 Syncing requirements to project repositories..."
if [ -d "cloned_repos" ]; then
    for repo in cloned_repos/*/; do
        if [ -d "$repo" ]; then
            repo_name=$(basename "$repo")
            echo "  📁 Checking $repo_name..."
            
            # Check if it's a git repository
            if git -C "$repo" status >/dev/null 2>&1; then
                cd "$repo" || continue
                
                if [ -n "$(git status --porcelain)" ]; then
                    echo "    🔄 Syncing requirements updates..."
                    git add requirements/ 2>/dev/null || git add . 2>/dev/null
                    if git commit -m "Requirements update: $(date '+%Y-%m-%d %H:%M:%S') - Timeline data sync" 2>/dev/null; then
                        echo "    ✅ Changes committed successfully"
                        echo "    🚀 Pushing to remote repository..."
                        if git push origin main 2>/dev/null; then
                            echo "    ✅ Successfully pushed to $repo_name repository"
                        else
                            echo "    ⚠️  Push failed - may need authentication or manual review"
                        fi
                    else
                        echo "    ⚠️  Commit failed - manual review needed"
                    fi
                else
                    echo "    ✅ Requirements up to date"
                fi
                
                cd - >/dev/null
            else
                echo "    ⏭️  Not a git repository"
            fi
        fi
    done
else
    echo "  ℹ️  No cloned repositories found"
fi

echo ""
echo "🎯 Next session - recommended workflow:"
echo "   1. make what-next (see current priorities)"
echo "   2. make prep PROJECT=<project> (prepare work environment)"
echo "   3. Continue development on recommended action"
echo ""
echo "🚀 Session closed safely - all changes pushed to remote repositories"