"""
User FastAPI Router
Auto-generated by tpl-backend-fastapi-crud
"""
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from models.user import User
from repositories.user_repository import UserRepository
from schemas.user_schemas import (
    UserCreate,
    UserUpdate,
    UserResponse,
)

# Dependency to get DB session (customize based on your setup)
def get_db():
    """Get database session - CUSTOMIZE THIS"""
    # Replace with your actual database session dependency
    raise NotImplementedError("Configure database session dependency")


router = APIRouter(
    prefix="/users",
    tags=["users"],
)


@router.get("/", response_model=List[UserResponse])
def list_users(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
):
    """List all users with pagination"""
    repo = UserRepository(db)
    items = repo.list(skip=skip, limit=limit)
    return items


@router.get("/{id}", response_model=UserResponse)
def get_user(
    id: int,
    db: Session = Depends(get_db),
):
    """Get User by ID"""
    repo = UserRepository(db)
    item = repo.get(id)
    
    if item is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"User with id {id} not found"
        )
    
    return item


@router.post("/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def create_user(
    data: UserCreate,
    db: Session = Depends(get_db),
):
    """Create new User"""
    repo = UserRepository(db)
    
    # Create model instance from schema
    obj = User(**data.model_dump())
    
    # Save to database
    created = repo.create(obj)
    return created


@router.put("/{id}", response_model=UserResponse)
def update_user(
    id: int,
    data: UserUpdate,
    db: Session = Depends(get_db),
):
    """Update User by ID"""
    repo = UserRepository(db)
    
    # Get update fields (exclude unset)
    update_data = data.model_dump(exclude_unset=True)
    
    # Update in database
    updated = repo.update(id, **update_data)
    
    if updated is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"User with id {id} not found"
        )
    
    return updated


@router.delete("/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user(
    id: int,
    db: Session = Depends(get_db),
):
    """Delete User by ID"""
    repo = UserRepository(db)
    
    success = repo.delete(id)
    
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"User with id {id} not found"
        )
    
    return None


@router.get("/count/total", response_model=dict)
def count_users(
    db: Session = Depends(get_db),
):
    """Get total count of users"""
    repo = UserRepository(db)
    count = repo.count()
    return {"count": count}
