"""
Item Repository
Auto-generated by tpl-backend-fastapi-crud
"""
from typing import Optional, List
from sqlalchemy.orm import Session

from models.user import Item


class ItemRepository:
    """Repository for Item CRUD operations"""
    
    def __init__(self, session: Session):
        self.session = session
    
    def get(self, id: int) -> Optional[Item]:
        """Get Item by ID"""
        return self.session.query(Item).filter(Item.id == id).one_or_none()
    
    def list(self, skip: int = 0, limit: int = 100) -> List[Item]:
        """List Item records with pagination"""
        return self.session.query(Item).offset(skip).limit(limit).all()
    
    def create(self, obj: Item) -> Item:
        """Create new Item"""
        self.session.add(obj)
        self.session.commit()
        self.session.refresh(obj)
        return obj
    
    def update(self, id: int, **fields) -> Optional[Item]:
        """Update Item by ID"""
        obj = self.get(id)
        if obj is None:
            return None
        
        for key, value in fields.items():
            if hasattr(obj, key):
                setattr(obj, key, value)
        
        self.session.commit()
        self.session.refresh(obj)
        return obj
    
    def delete(self, id: int) -> bool:
        """Delete Item by ID"""
        obj = self.get(id)
        if obj is None:
            return False
        
        self.session.delete(obj)
        self.session.commit()
        return True
    
    def count(self) -> int:
        """Count total Item records"""
        return self.session.query(Item).count()
    
    def get_by_email(self, email: str) -> Optional[Item]:
        """Get Item by email"""
        return self.session.query(Item).filter(Item.email == email).one_or_none()
    
    def get_by_username(self, username: str) -> Optional[Item]:
        """Get Item by username"""
        return self.session.query(Item).filter(Item.username == username).one_or_none()
