"""
Item FastAPI Router
Auto-generated by tpl-backend-fastapi-crud
"""
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from models.user import Item
from repositories.user_repository import ItemRepository
from schemas.user_schemas import (
    ItemCreate,
    ItemUpdate,
    ItemResponse,
)

# Dependency to get DB session (customize based on your setup)
def get_db():
    """Get database session - CUSTOMIZE THIS"""
    # Replace with your actual database session dependency
    raise NotImplementedError("Configure database session dependency")


router = APIRouter(
    prefix="/items",
    tags=["items"],
)


@router.get("/", response_model=List[ItemResponse])
def list_items(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
):
    """List all items with pagination"""
    repo = ItemRepository(db)
    items = repo.list(skip=skip, limit=limit)
    return items


@router.get("/{id}", response_model=ItemResponse)
def get_user(
    id: int,
    db: Session = Depends(get_db),
):
    """Get Item by ID"""
    repo = ItemRepository(db)
    item = repo.get(id)
    
    if item is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Item with id {id} not found"
        )
    
    return item


@router.post("/", response_model=ItemResponse, status_code=status.HTTP_201_CREATED)
def create_user(
    data: ItemCreate,
    db: Session = Depends(get_db),
):
    """Create new Item"""
    repo = ItemRepository(db)
    
    # Create model instance from schema
    obj = Item(**data.model_dump())
    
    # Save to database
    created = repo.create(obj)
    return created


@router.put("/{id}", response_model=ItemResponse)
def update_user(
    id: int,
    data: ItemUpdate,
    db: Session = Depends(get_db),
):
    """Update Item by ID"""
    repo = ItemRepository(db)
    
    # Get update fields (exclude unset)
    update_data = data.model_dump(exclude_unset=True)
    
    # Update in database
    updated = repo.update(id, **update_data)
    
    if updated is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Item with id {id} not found"
        )
    
    return updated


@router.delete("/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user(
    id: int,
    db: Session = Depends(get_db),
):
    """Delete Item by ID"""
    repo = ItemRepository(db)
    
    success = repo.delete(id)
    
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Item with id {id} not found"
        )
    
    return None


@router.get("/count/total", response_model=dict)
def count_items(
    db: Session = Depends(get_db),
):
    """Get total count of items"""
    repo = ItemRepository(db)
    count = repo.count()
    return {"count": count}
