"""
Item Pydantic Schemas
Auto-generated by tpl-backend-fastapi-crud
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, EmailStr

class ItemBase(BaseModel):
    """Base Item schema with common attributes"""
    email: str
    username: str
    full_name: Optional[str] = None
    is_active: bool = True
    is_superuser: bool = False

class ItemCreate(ItemBase):
    """Schema for creating Item"""
    pass


class ItemUpdate(BaseModel):
    """Schema for updating Item (all fields optional)"""
    email: Optional[str] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None
    is_superuser: Optional[bool] = None


class ItemInDB(ItemBase):
    """Schema for Item as stored in database"""
    id: int
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class ItemResponse(ItemInDB):
    """Schema for Item in API responses"""
    pass
