[windows_machine]
host = "172.22.177.213"
username = "James Fleming"
xml_workspace = "C:/control_tower/xml_workspace"
ms_project_workspace = "C:/control_tower/ms_project"

[network]
ssh_key = ""
use_admin_shares = true
network_drive = ""
windows_share_path = "\\\\172.22.177.213\\c$\\control_tower"

[ms_project]
main_project_file = "C:/control_tower/ms_project/ZnNi Line Development Plan-08.xml"
standalone_xml_location = "C:/control_tower/xml_workspace/SF_Investment_Strategy_OEE_OLE_Application_Schedule.xml"

[codespaces]
xml_workspace = "/workspaces/control_tower/cloned_repos/contract_projects/xml_workspace"

