"""
User Repository
Auto-generated by tpl-backend-fastapi-crud
"""
from typing import Optional, List
from sqlalchemy.orm import Session

from models.user import User


class UserRepository:
    """Repository for User CRUD operations"""
    
    def __init__(self, session: Session):
        self.session = session
    
    def get(self, id: int) -> Optional[User]:
        """Get User by ID"""
        return self.session.query(User).filter(User.id == id).one_or_none()
    
    def list(self, skip: int = 0, limit: int = 100) -> List[User]:
        """List User records with pagination"""
        return self.session.query(User).offset(skip).limit(limit).all()
    
    def create(self, obj: User) -> User:
        """Create new User"""
        self.session.add(obj)
        self.session.commit()
        self.session.refresh(obj)
        return obj
    
    def update(self, id: int, **fields) -> Optional[User]:
        """Update User by ID"""
        obj = self.get(id)
        if obj is None:
            return None
        
        for key, value in fields.items():
            if hasattr(obj, key):
                setattr(obj, key, value)
        
        self.session.commit()
        self.session.refresh(obj)
        return obj
    
    def delete(self, id: int) -> bool:
        """Delete User by ID"""
        obj = self.get(id)
        if obj is None:
            return False
        
        self.session.delete(obj)
        self.session.commit()
        return True
    
    def count(self) -> int:
        """Count total User records"""
        return self.session.query(User).count()
    
    def get_by_email(self, email: str) -> Optional[User]:
        """Get User by email"""
        return self.session.query(User).filter(User.email == email).one_or_none()
    
    def get_by_username(self, username: str) -> Optional[User]:
        """Get User by username"""
        return self.session.query(User).filter(User.username == username).one_or_none()
