/**
 * Hero Section Component
 * Auto-generated by tpl-frontend-react-landing
 */
import React from 'react';

export const Hero: React.FC = () => {
  const handlePrimaryCTA = () => {
    // TODO: Implement primary CTA action
    console.log('Primary CTA clicked');
  };

  const handleSecondaryCTA = () => {
    // TODO: Implement secondary CTA action
    console.log('Secondary CTA clicked');
  };

  return (
    <section className="relative overflow-hidden py-20 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          {/* Brand/Logo */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-indigo-600">
              MVPBuilder
            </h2>
          </div>

          {/* Headline */}
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
            Build Your MVP in Minutes, Not Months
          </h1>

          {/* Subtitle */}
          <p className="mt-6 text-lg leading-8 text-gray-600">
            Generate production-ready code with AI-powered templates. Ship faster, validate ideas quicker, and focus on what matters.
          </p>

          {/* CTAs */}
          <div className="mt-10 flex items-center justify-center gap-x-6">
            <button
              onClick={handlePrimaryCTA}
              className="rounded-md bg-indigo-600 px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 transition-colors"
            >
              Start Free Trial
            </button>
            <button
              onClick={handleSecondaryCTA}
              className="text-sm font-semibold leading-6 text-gray-900 hover:text-gray-700 transition-colors"
            >
              See Demo <span aria-hidden="true">→</span>
            </button>
          </div>

          {/* Social Proof (Optional) */}
          <div className="mt-10 flex items-center justify-center gap-x-6 text-sm text-gray-500">
            <p>✨ Trusted by 1000+ users</p>
            <p>⚡ 5-minute setup</p>
            <p>🔒 Enterprise security</p>
          </div>
        </div>
      </div>

      {/* Background decorations */}
      <div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
        <div className="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-indigo-200 to-purple-200 opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" />
      </div>
    </section>
  );
};

export default Hero;
