/**
 * LandingPage - Landing Page
 * Auto-generated by tpl-frontend-react-landing
 */
import React from 'react';
import Hero from './Hero';
import Features from './Features';
import EmailCapture from './EmailCapture';

interface LandingPageProps {
  className?: string;
}

export const LandingPage: React.FC<LandingPageProps> = ({ className = '' }) => {
  return (
    <div className={`min-h-screen bg-gradient-to-b from-white to-gray-50 ${className}`}>
      <Hero />
      <Features />
<EmailCapture />    </div>
  );
};

export default LandingPage;
