#!/bin/bash
# Control Tower Quick Commands
# Easy shortcuts for everyday project management

echo "🏗️ Control Tower Quick Commands"
echo "================================"
echo ""
echo "🎯 MS PROJECT SYSTEM (Recommended):"
echo "  python3 control_tower.py ms-project --action status      - Project overview"
echo "  python3 control_tower.py ms-project --action milestones  - Current milestones"
echo "  python3 control_tower.py ms-project --action overdue     - Overdue tasks"
echo "  python3 control_tower.py ms-project --action reports     - Query statistics"
echo "  python3 control_tower.py ms-project --action sync        - Sync from MS Project"
echo ""
echo "📊 REPORTING FEATURES:"
echo "  • All queries automatically generate timestamped reports"
echo "  • Reports saved to: /workspaces/control_tower/reporting/"
echo "  • Reusable commands saved to: control_tower_commands.md"
echo "  • Query tracking prevents duplicate command generation"
echo ""
echo "📅 DAILY QUERIES (CSV Legacy):"
echo "  python3 control_tower.py csv today      - What's due today"
echo "  python3 control_tower.py csv week       - What's due this week"
echo "  python3 control_tower.py csv overdue    - Show overdue tasks"
echo ""
echo "🎯 MILESTONE TRACKING:"
echo "  python3 control_tower.py csv milestones         - Next 30 days"
echo "  python3 control_tower.py csv milestones --days 7 - Next 7 days"
echo ""
echo "👤 PERSONAL TASKS:"
echo "  python3 control_tower.py csv tasks --person 'Your Name' - Your tasks"
echo ""
echo "🛠️ UTILITIES:"
echo "  python3 control_tower.py util demo     - See Control Tower in action"
echo "  python3 control_tower.py util roadmap  - Development roadmap"
echo "  python3 control_tower.py util help     - This help screen"
echo ""
echo "🚀 QUICK EXAMPLES:"
echo "=================="
echo ""
echo "📅 What's happening today:"
echo "python3 control_tower.py ms-project --action status"
echo ""
echo "📊 Check overdue items:"
echo "python3 control_tower.py ms-project --action overdue --limit 10"
echo ""
echo "🎯 View current milestones:"
echo "python3 control_tower.py ms-project --action milestones --period current"
echo ""
echo "📋 See all your saved commands:"
echo "cat reporting/control_tower_commands.md"
