/**
 * Amplitude React Integration
 * 
 * Generated by: tpl-analytics-amplitude
 * App: My SaaS App
 * 
 * Usage in React:
 *   import { AmplitudeProvider, useAmplitude } from './analytics/amplitude-react';
 *   
 *   // Wrap your app
 *   <AmplitudeProvider>
 *     <App />
 *   </AmplitudeProvider>
 *   
 *   // Use in components
 *   const { trackEvent } = useAmplitude();
 *   trackEvent('button_clicked', { button_name: 'signup' });
 */

import React, { createContext, useContext, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { initializeAmplitude } from './amplitude-config';
import { 
  trackEvent, 
  trackPageview, 
  identifyUser,
  setUserProperties,
  AmplitudeEvents 
} from './amplitude-events';

interface AmplitudeContextType {
  trackEvent: typeof trackEvent;
  trackPageview: typeof trackPageview;
  identifyUser: typeof identifyUser;
  setUserProperties: typeof setUserProperties;
  events: typeof AmplitudeEvents;
}

const AmplitudeContext = createContext<AmplitudeContextType | null>(null);

/**
 * Amplitude Provider Component
 * Initializes Amplitude and provides tracking functions via context
 */
export function AmplitudeProvider({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    // Initialize Amplitude on mount
    initializeAmplitude();
  }, []);

  const value: AmplitudeContextType = {
    trackEvent,
    trackPageview,
    identifyUser,
    setUserProperties,
    events: AmplitudeEvents,
  };

  return <AmplitudeContext.Provider value={value}>{children}</AmplitudeContext.Provider>;
}

/**
 * Hook to access Amplitude tracking functions
 */
export function useAmplitude(): AmplitudeContextType {
  const context = useContext(AmplitudeContext);
  if (!context) {
    throw new Error('useAmplitude must be used within AmplitudeProvider');
  }
  return context;
}

/**
 * Component to auto-track pageviews with React Router
 * Place this inside your Router component
 */
export function AmplitudePageviewTracker() {
  const location = useLocation();

  useEffect(() => {
    // Track pageview on route change
    trackPageview(location.pathname + location.search);
  }, [location]);

  return null;
}

/**
 * HOC to track component views
 */
export function withAmplitudeTracking<P extends object>(
  Component: React.ComponentType<P>,
  componentName: string
) {
  return function AmplitudeTrackedComponent(props: P) {
    useEffect(() => {
      trackEvent('component_viewed', { component_name: componentName });
    }, []);

    return <Component {...props} />;
  };
}

/**
 * Component to track button clicks
 */
interface AmplitudeButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  eventName?: string;
  eventProperties?: Record<string, any>;
  children: React.ReactNode;
}

export function AmplitudeButton({ 
  eventName = 'button_clicked', 
  eventProperties = {}, 
  onClick,
  children,
  ...props 
}: AmplitudeButtonProps) {
  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    trackEvent(eventName, eventProperties);
    onClick?.(e);
  };

  return (
    <button onClick={handleClick} {...props}>
      {children}
    </button>
  );
}

/**
 * Component to track link clicks
 */
interface AmplitudeLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  eventProperties?: Record<string, any>;
  children: React.ReactNode;
}

export function AmplitudeLink({ 
  eventProperties = {}, 
  onClick,
  href,
  children,
  ...props 
}: AmplitudeLinkProps) {
  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    trackEvent('link_clicked', { link_url: href, ...eventProperties });
    onClick?.(e);
  };

  return (
    <a href={href} onClick={handleClick} {...props}>
      {children}
    </a>
  );
}
