/**
 * Google Analytics 4 Configuration
 * 
 * Generated by: tpl-analytics-ga4
 * App: My SaaS App
 * Environment: production
 */

// GA4 Measurement ID (from environment variable)
export const GA4_MEASUREMENT_ID = import.meta.env.VITE_GA4_MEASUREMENT_ID || 'G-ABC123DEF4';
export const GA4_DEBUG = false;
export const APP_NAME = 'My SaaS App';
export const ENVIRONMENT = 'production';

/**
 * Initialize Google Analytics 4
 * Call this once in your app entry point (main.tsx or App.tsx)
 */
export function initializeGA4() {
  // Only initialize in browser environment
  if (typeof window === 'undefined') {
    return;
  }

  // Check if measurement ID is configured
  if (!GA4_MEASUREMENT_ID || GA4_MEASUREMENT_ID.startsWith('G-') === false) {
    console.warn('GA4: Measurement ID not configured. Tracking disabled.');
    return;
  }

  // Load gtag.js script
  const script = document.createElement('script');
  script.async = true;
  script.src = `https://www.googletagmanager.com/gtag/js?id=${GA4_MEASUREMENT_ID}`;
  document.head.appendChild(script);

  // Initialize dataLayer
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    window.dataLayer.push(arguments);
  }
  window.gtag = gtag;

  // Configure GA4
  gtag('js', new Date());
  gtag('config', GA4_MEASUREMENT_ID, {
    app_name: APP_NAME,
    debug_mode: GA4_DEBUG,
    send_page_view: true, // Auto-track pageviews
  });

  console.log(`✅ GA4 initialized: ${GA4_MEASUREMENT_ID}`);
}

/**
 * Check if GA4 is loaded and ready
 */
export function isGA4Ready() {
  return typeof window !== 'undefined' && 
         typeof window.gtag === 'function' && 
         GA4_MEASUREMENT_ID.startsWith('G-');
}

/**
 * Get current GA4 client ID
 */
export function getClientId() {
  return new Promise((resolve) => {
    if (!isGA4Ready()) {
      resolve(null);
      return;
    }

    window.gtag('get', GA4_MEASUREMENT_ID, 'client_id', (clientId) => {
      resolve(clientId);
    });
  });
}
