/**
 * Amplitude Analytics Configuration
 * 
 * Generated by: tpl-analytics-amplitude
 * App: My SaaS App
 * Environment: production
 * 
 * Loads Amplitude dynamically from CDN (no npm dependency required)
 */

// Amplitude API Key (from environment variable)
export const AMPLITUDE_API_KEY = import.meta.env.VITE_AMPLITUDE_API_KEY || 'abc123def456ghi789jkl';
export const AMPLITUDE_DEBUG = false;
export const APP_NAME = 'My SaaS App';
export const ENVIRONMENT = 'production';

let isInitialized = false;
let isScriptLoaded = false;

/**
 * Load Amplitude script from CDN
 */
function loadAmplitudeScript() {
  return new Promise((resolve, reject) => {
    // Check if already loaded
    if (isScriptLoaded || window.amplitude) {
      resolve();
      return;
    }

    // Create script element
    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.src = 'https://cdn.amplitude.com/libs/analytics-browser-2.3.8-min.js.gz';
    
    script.onload = () => {
      isScriptLoaded = true;
      resolve();
    };
    
    script.onerror = () => {
      console.error('Failed to load Amplitude script');
      reject(new Error('Failed to load Amplitude'));
    };

    // Append to head
    document.head.appendChild(script);
  });
}

/**
 * Initialize Amplitude
 * Call this once in your app entry point (main.tsx or App.tsx)
 */
export async function initializeAmplitude() {
  // Only initialize in browser environment
  if (typeof window === 'undefined') {
    return;
  }

  // Check if API key is configured
  if (!AMPLITUDE_API_KEY || AMPLITUDE_API_KEY.length < 10) {
    console.warn('Amplitude: API key not configured. Tracking disabled.');
    return;
  }

  // Avoid double initialization
  if (isInitialized) {
    return;
  }

  try {
    // Load Amplitude script
    await loadAmplitudeScript();

    // Initialize Amplitude
    window.amplitude.init(AMPLITUDE_API_KEY, undefined, {
      logLevel: AMPLITUDE_DEBUG ? 1 : 3, // 1 = Debug, 3 = Warn
      defaultTracking: {
        sessions: true,
        pageViews: true,
        formInteractions: false,
        fileDownloads: false,
      },
    });

    // Set user properties that apply to all events
    const identifyEvent = new window.amplitude.Identify();
    identifyEvent.set('app_name', APP_NAME);
    identifyEvent.set('environment', ENVIRONMENT);
    window.amplitude.identify(identifyEvent);

    isInitialized = true;
    console.log(`✅ Amplitude initialized: ${AMPLITUDE_API_KEY.substring(0, 8)}...`);
  } catch (error) {
    console.error('Failed to initialize Amplitude:', error);
  }
}

/**
 * Check if Amplitude is loaded and ready
 */
export function isAmplitudeReady() {
  return isInitialized && window.amplitude;
}

/**
 * Get Amplitude SDK instance
 */
export function getAmplitude() {
  return window.amplitude;
}

/**
 * Get current device ID
 */
export function getDeviceId() {
  return window.amplitude?.getDeviceId();
}

/**
 * Get current session ID
 */
export function getSessionId() {
  return window.amplitude?.getSessionId();
}

/**
 * Reset Amplitude (logout)
 */
export function resetAmplitude() {
  if (window.amplitude) {
    window.amplitude.reset();
  }
}

/**
 * Set user ID
 */
export function setUserId(userId) {
  if (window.amplitude) {
    window.amplitude.setUserId(userId);
  }
}
