/**
 * Mixpanel Analytics Configuration
 * 
 * Generated by: tpl-analytics-mixpanel
 * App: My SaaS App
 * Environment: production
 */

import mixpanel from 'mixpanel-browser';

// Mixpanel Project Token (from environment variable)
export const MIXPANEL_TOKEN = import.meta.env.VITE_MIXPANEL_TOKEN || 'abc123def456ghi789';
export const MIXPANEL_DEBUG = false;
export const APP_NAME = 'My SaaS App';
export const ENVIRONMENT = 'production';

let isInitialized = false;

/**
 * Initialize Mixpanel
 * Call this once in your app entry point (main.tsx or App.tsx)
 */
export function initializeMixpanel() {
  // Only initialize in browser environment
  if (typeof window === 'undefined') {
    return;
  }

  // Check if token is configured
  if (!MIXPANEL_TOKEN || MIXPANEL_TOKEN.length < 10) {
    console.warn('Mixpanel: Token not configured. Tracking disabled.');
    return;
  }

  // Avoid double initialization
  if (isInitialized) {
    return;
  }

  // Initialize Mixpanel
  mixpanel.init(MIXPANEL_TOKEN, {
    debug: MIXPANEL_DEBUG,
    track_pageview: true,
    persistence: 'localStorage',
    ignore_dnt: false,
    loaded: function(mixpanel) {
      // Set super properties (sent with every event)
      mixpanel.register({
        app_name: APP_NAME,
        environment: ENVIRONMENT,
      });
    }
  });

  isInitialized = true;
  console.log(`✅ Mixpanel initialized: ${MIXPANEL_TOKEN.substring(0, 8)}...`);
}

/**
 * Check if Mixpanel is loaded and ready
 */
export function isMixpanelReady() {
  return isInitialized && typeof mixpanel !== 'undefined';
}

/**
 * Get Mixpanel instance
 */
export function getMixpanel() {
  if (!isMixpanelReady()) {
    console.warn('Mixpanel: Not initialized');
    return null;
  }
  return mixpanel;
}

/**
 * Get current Mixpanel distinct ID
 */
export function getDistinctId() {
  const mp = getMixpanel();
  return mp ? mp.get_distinct_id() : null;
}

/**
 * Reset Mixpanel (logout)
 */
export function resetMixpanel() {
  const mp = getMixpanel();
  if (mp) {
    mp.reset();
  }
}
