"""
User SQLAlchemy Model
Auto-generated by tpl-backend-fastapi-crud
"""
from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, Text, JSON, func
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class User(Base):
    """User database model"""
    
    __tablename__ = "users"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # Custom fields
    email = Column(
        String,
        nullable=False,
        unique=True,
        index=True,
    )
    username = Column(
        String,
        nullable=False,
        unique=True,
        index=True,
    )
    full_name = Column(
        String,
        nullable=True,
    )
    is_active = Column(
        Boolean,
        nullable=False,
        default=True,
    )
    is_superuser = Column(
        Boolean,
        nullable=False,
        default=False,
    )
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    def __repr__(self):
        return f"<User(id={self.id})>"
